swagger: "2.0"
info:
  description: "This is a sample Customer Publisher Microservice"
  version: "1.0.0"
  title: "Customer Publisher"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "pkglobal.swagger.io"
basePath: "/v1/customer"
schemes:
  - "https"
  - "http"
paths:
  /publish:
    post:
      tags:
        - "publish"
      summary: "Publish Message to Kafka"
      description: ""
      operationId: "publishMessage"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/json"
        - "application/xml"
      parameters:
        - name: "Authorization"
          in: "header"
          description: "Token for Authorization"
          required: true
          type: "string"
          default: "Authorization"
        - name: "Transaction-Id"
          in: "header"
          description: "transaction Id"
          required: true
          type: "string"
          default: "transactionId"
        - name: "Activity-Id"
          in: "header"
          description: "Unique Identifier for the request"
          required: true
          type: "string"
          default: "d7845679-4578-8972-7234-bg589374"
        - in: "body"
          name: "body"
          description: "Consume the request and publish it to Kafka"
          required: true
          schema:
            $ref: "#/definitions/Customer"
      responses:
        "200":
          description: "Success Response"
          schema:
            $ref: "#/definitions/CustomerSuccessResponse"
        "400":
          description: "Failure Response"
          schema:
            $ref: "#/definitions/CustomerFailureResponse"
        "401":
          description: "Failure Response"
          schema:
            $ref: "#/definitions/CustomerFailureResponse"
        "404":
          description: "Failure Response"
          schema:
            $ref: "#/definitions/CustomerFailureResponse"
        "500":
          description: "Failure Response"
          schema:
            $ref: "#/definitions/CustomerFailureResponse"
securityDefinitions:
  customer_auth:
    type: "oauth2"
    authorizationUrl: "http://abc.swagger.io/oauth/dialog"
    flow: "implicit"
definitions:
  Customer:
    type: "object"
    required:
      - "customerNumber"
      - "firstName"
      - "lastName"
      - "birthDate"
      - "country"
      - "countryCode"
      - "mobileNumber"
      - "email;"
      - "customerStatus"
      - "address"
    properties:
      customerNumber:
        type: "string"
      firstName:
        type: "string"
      lastname:
        type: "string"
      birthdate:
        type: "string"
        format: "date-time"
      country:
        type: "string"
      countryCode:
        type: "string"
      mobileNumber:
        type: "integer"
        format: "int32"
      email:
        type: "string"
      customerStatus:
        type: "string"
        enum:
          - "open"
          - "close"
          - "suspended"
          - "restored"
      address:
        $ref: "#/definitions/Address"
    xml:
      name: "Customer"
  Address:
    type: "object"
    required:
      - "addressLine1"
    properties:
      addressLine1:
        type: "string"
      addressLine2:
        type: "string"
      street:
        type: "string"
      postalCode:
        type: "integer"
        format: "int32"
    xml:
      name: "Address"
  CustomerSuccessResponse:
    type: "object"
    required:
      - "status"
    properties:
      status:
        type: "string"
        default: "success"
      message:
        type: "string"
    xml:
      name: "CustomerSuccessResponse"
  CustomerFailureResponse:
    type: "object"
    required:
      - "status"
    properties:
      status:
        type: "string"
        default: "error"
      message:
        type: "string"
      error_type:
        type: "string"
        default: "GeneralException"
    xml:
      name: "CustomerFailureResponse"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"